# Please insert new items alphabetically.

apps:
  members:
    - rromanchenko
    - flindeman
    - aroschupkin

  channel:
    "#apps"

  quotes:
    - ":wave:"

lighthouse:
  members:
    - adigrabcad
    - chris-grabcad
    - bitosome
    - DanielDignam
    - NigelAtGrabCAD

  channel:
    "#lighthouse"

  quotes:
    - ":wave:"

octopus:
  members:
    - EyalRaz
    - Jittery
    - arielhad
    - csidorchuk
    - zhelezina
    - mklchum

  channel:
    "#secret-octopus-team"

  quotes:
    - ":wave:"
  
solutions:
  members:
    - atardugno
    - vtravieso
    - urimike

  channel:
    "#solutions"

  quotes:
    - ":wave:"
