# Please insert new items alphabetically.

coyote:
  members:
    - nk327
    - hmak3d
    - tatianagrabcad

  channel:
    "#coyote-private"

  quotes:
    - ":wave:"

deathclaw:
  members:
    - hmak3d
    - evan-grabcad
    - Maxodactyl
    - caseprince

  channel:
    "#deathclaw-core"

  quotes:
    - ":wave:"

lighthouse:
  members:
    - chris-grabcad
    - NigelAtGrabCAD
    - EmaParodi
    - zhelezina
    - DanielDignam
    - robert-may1

  channel:
    "#lighthouse"

  quotes:
    - ":wave:"

machine:
  members:
    - priitm
    - csidorchuk

  channel:
    "#machine"

  quotes:
    - ":wave:"

octopus:
  members:
    - arielhad
    - mklchum
    - adigrabcad
    - orivainer
    - forzesed
    - EyalRaz
    - Jittery

  channel:
    "#octopus"

  quotes:
    - ":wave:"

solutions:
  members:
    - atardugno
    - vtravieso
    - ShaiTubul
    - yossikoren
    - urimike

  channel:
    "#solutions"

  quotes:
    - ":wave:"

lacheetah:
  members:
    - raidokaldma
    - joras
    - meelispr
    - amPerl

  channel:
    "#la-cheetah"

spock:
  members:
    - mlni
    - johannessiig
    - tambet
  channel:
    "#spock-notifications"

pelican:
  members:
    - jaxer
    - mwhearty

  channel:
    "#pelican"
    
photon:
  members:
    - jeffmisu
    - posulliv
    - bcourter

  channel:
    "#photon"
