# Please insert new items alphabetically.

lighthouse:
  members:
    - adigrabcad
    - atardugno
    - bitosome
    - danieldignam
    - robert-may1
    - zhelezina

  channel:
    "#lighthouse"

  quotes:
    - ":wave:"
