# Please insert new items alphabetically.

apps:
  members:
    - rromanchenko
    - flindeman

  channel:
    "#apps"

  quotes:
    - ":wave:"

fox:
  members:
    - flindeman
    - aroschupkin
    - OlegMiroshnichenko
    - s7sorin

  channel:
    "#eaglesolidworksaddin"

  quotes:
    - ":wave:"

lighthouse:
  members:
    - adigrabcad
    - chris-grabcad
    - bitosome
    - DanielDignam
    - NigelAtGrabCAD

  channel:
    "#lighthouse"

  quotes:
    - ":wave:"

machine:
  members:
    - zhelezina
    - robert-may1

  channel:
    "#machine"

  quotes:
    - ":wave:"  

octopus:
  members:
    - EyalRaz
    - Jittery
    - arielhad
    - csidorchuk
    - novice3030
    - mklchum

  channel:
    "#secret-octopus-team"

  quotes:
    - ":wave:"
  
solutions:
  members:
    - atardugno
    - vtravieso
    - urimike

  channel:
    "#solutions"

  quotes:
    - ":wave:"

lacheetah:
  members:
    - mlni
    - raidokaldma
    - jaxer
    - joras
    - meelispr

  channel:
    "#la-cheetah"
