# Please insert new items alphabetically.

tribble:
  members:
    - Maxodactyl
    - caseprince
    - reshadbinharun
    - mwhearty
    - posulliv
    - anju-james

  channel:
    "#tribble-private"

  quotes:
    - ":wave:"

lighthouse:
  members:
    - NigelAtGrabCAD
    - DavidJohnMcLean

  channel:
    "#lighthouse"

  quotes:
    - ":wave:"

spock:
  members:
    - johannessiig
    - tambet
  channel:
    "#spock-notifications"

jackalope:
  members:
    - mrk252
    - evan-grabcad
    - vtravieso
    - RobertMJ

  channel:
    "#jackalope"

alpha:
  members:
    - erikheide
    - dholzwarth

  channel:
    "#alpha"

  quotes:
    - ":wave:"

kirin:
  members:
    - NigelAtGrabCAD
    - DavidJohnMcLean
    - jaySSYS
    - deyaoren
    - jeremyhovis

  channel:
    "#kirin-notifications"

  quotes:
    - ":wave:"
    