# Please insert new items alphabetically.

deathclaw:
  members:
    - hmak3d
    - evan-grabcad
    - Maxodactyl
    - caseprince

  channel:
    "#deathclaw-core"

  quotes:
    - ":wave:"

lighthouse:
  members:
    - chris-grabcad
    - NigelAtGrabCAD
    - robert-may1
    - hhazi
    - dangrabcad

  channel:
    "#lighthouse"

  quotes:
    - ":wave:"

machine:
  members:
    - priitm
    - hmak3d

  channel:
    "#machine"

  quotes:
    - ":wave:"

octopus:
  members:
    - arielhad
    - ido-ran
    - Tamara211
    - danielyac
    - manuel-grabcad
    - amPerl
    - YairFuchs
    - prime-initiative 

  channel:
    "#octopus"

  quotes:
    - ":wave:"

solutions:
  members:
    - urimike
    - AvivEshed
    - slavashtilerman

  channel:
    "#solutions"

  quotes:
    - ":wave:"

lacheetah:
  members:
    - raidokaldma
    - mlni
    - meelispr

  channel:
    "#la-cheetah"

spock:
  members:
    - johannessiig
    - tambet
  channel:
    "#spock-notifications"

pelican:
  members:
    - jaxer
    - mwhearty

  channel:
    "#pelican"
    
jackalope:
  members:
    - jeffmisu
    - posulliv

  channel:
    "#jackalope"

carpenters:
  members:
    - atardugno
    - vtravieso

  channel:
    "#carpenters"
