# Please insert new items alphabetically.

lighthouse:
  members:
    - adigrabcad
    - atardugno
    - bitosome
    - DanielDignam
    - robert-may1
    - zhelezina

  channel:
    "#lighthouse"

  quotes:
    - ":wave:"

octopus:
  members:
    - NigelAtGrabCAD
    - EyalRaz
    - Jittery
    - arielhad

  channel:
    "#secret-octopus-team"

  quotes:
    - ":wave:"
