# Please insert new items alphabetically.

lighthouse:
  members:
    - adigrabcad
    - atardugno
    - bitosome
    - DanielDignam
    - robert-may1
    - zhelezina

  channel:
    "#lighthouse"

  quotes:
    - ":wave:"

apps:
  members:
    - OwenOrsini
    - rromanchenko
    - flindeman

  channel:
    "#apps"

  quotes:
    - ":wave:"
