# Please insert new items alphabetically.

apps:
  members:
    - rromanchenko
    - flindeman

  channel:
    "#apps"

  quotes:
    - ":wave:"

fox:
  members:
    - flindeman
    - aroschupkin
    - OlegMiroshnichenko
    - s7sorin

  channel:
    “#eaglesolidworksaddin”

  quotes:
    - ":wave:"

lighthouse:
  members:
    - adigrabcad
    - atardugno
    - bitosome
    - DanielDignam
    - NigelAtGrabCAD

  channel:
    "#lighthouse"

  quotes:
    - ":wave:"

octopus:
  members:
    - EyalRaz
    - Jittery
    - arielhad
    - csidorchuk
    - zhelezina
    - mklchum

  channel:
    "#secret-octopus-team"

  quotes:
    - ":wave:"
