# Please insert new items alphabetically.

deathclaw:
  members:
    - hmak3d
    - evan-grabcad
    - Maxodactyl
    - caseprince

  channel:
    "#deathclaw-core"

  quotes:
    - ":wave:"

lighthouse:
  members:
    - chris-grabcad
    - NigelAtGrabCAD
    - EmaParodi
    - zhelezina
    - DanielDignam
    - robert-may1

  channel:
    "#lighthouse"

  quotes:
    - ":wave:"

machine:
  members:
    - priitm
    - meelispr
    - hmak3d

  channel:
    "#machine"

  quotes:
    - ":wave:"

octopus:
  members:
    - arielhad
    - mklchum
    - orivainer
    - danielyac
    - manuel-grabcad
    - amPerl
    - YairFuchs
    - prime-initiative 

  channel:
    "#octopus"

  quotes:
    - ":wave:"

solutions:
  members:
    - urimike
    - AvivEshed

  channel:
    "#solutions"

  quotes:
    - ":wave:"

lacheetah:
  members:
    - raidokaldma
    - mlni

  channel:
    "#la-cheetah"

spock:
  members:
    - johannessiig
    - tambet
  channel:
    "#spock-notifications"

pelican:
  members:
    - jaxer
    - mwhearty

  channel:
    "#pelican"
    
jackalope:
  members:
    - jeffmisu
    - posulliv

  channel:
    "#jackalope"
