# Please insert new items alphabetically.

tribble:
  members:
    - evan-grabcad
    - Maxodactyl
    - caseprince
    - reshadbinharun
    - mwhearty
    - anju-james

  channel:
    "#tribble-private"

  quotes:
    - ":wave:"

lighthouse:
  members:
    - NigelAtGrabCAD
    - robert-may1
    - DavidJohnMcLean

  channel:
    "#lighthouse"

  quotes:
    - ":wave:"

machine:
  members:
    - posulliv    
    - chris-grabcad

  channel:
    "#machine"

  quotes:
    - ":wave:"

octopus:
  members:
    - arielhad
    - ido-ran
    - Tamara211
    - danielyac
    - manuel-grabcad
    - amPerl
    - YairFuchs
    - dmitri-grabcad

  channel:
    "#octopus"

  quotes:
    - ":wave:"

solutions:
  members:
    - urimike
    - AvivEshed
    - slavashtilerman

  channel:
    "#solutions"

  quotes:
    - ":wave:"

lacheetah:
  members:
    - lalomartins
    - jaxer

  channel:
    "#la-cheetah"

spock:
  members:
    - johannessiig
    - tambet
  channel:
    "#spock-notifications"

jackalope:
  members:
    - jeffmisu
    - mrk252
    - dangrabcad
    - hhazi
    - TiptonBR

  channel:
    "#jackalope"

carpenters:
  members:
    - atardugno
    - vtravieso

  channel:
    "#carpenters"
    
alpha:
  members:
    - jaySSYS
    - erikheide
    - deyaoren
    
  channel:
    "#alpha"

voyager:
  members:
    - priitm
    - AlexRevin
    - blabounty
    - lackovic
    - hmak3d
    
  channel:
    "#voyager-notifications"
    
geometry:
  members:
    - NigelAtGrabCAD
    - robert-may1
    - hhazi
    - dangrabcad
    - atardugno
    - vtravieso
    - jeffmisu
    - TiptonBR
    - mrk252

  channel:
    "#geometry"

  quotes:
    - ":wave:"
