# Please insert new items alphabetically.

deathclaw:
  members:
    - hmak3d
    - evan-grabcad
    - Maxodactyl
    - caseprince

  channel:
    "#deathclaw-core"

  quotes:
    - ":wave:"

lighthouse:
  members:
    - chris-grabcad
    - NigelAtGrabCAD
    - EmaParodi
    - zhelezina
    - DanielDignam
    - robert-may1

  channel:
    "#lighthouse"

  quotes:
    - ":wave:"

machine:
  members:
    - priitm
    - csidorchuk

  channel:
    "#machine"

  quotes:
    - ":wave:"

octopus:
  members:
    - arielhad
    - mklchum
    - adigrabcad
    - orivainer
    - EyalRaz
    - danielyac

  channel:
    "#octopus"

  quotes:
    - ":wave:"

solutions:
  members:
    - atardugno
    - vtravieso
    - ShaiTubul
    - yossikoren
    - urimike

  channel:
    "#solutions"

  quotes:
    - ":wave:"

lacheetah:
  members:
    - raidokaldma
    - joras
    - meelispr

  channel:
    "#la-cheetah"

spock:
  members:
    - mlni
    - johannessiig
    - tambet
  channel:
    "#spock-notifications"

pelican:
  members:
    - jaxer
    - mwhearty

  channel:
    "#pelican"
    
jackalope:
  members:
    - jeffmisu
    - posulliv

  channel:
    "#jackalope"
