# Please insert new items alphabetically.

deathclaw:
  members:
    - priitm
    - evan-grabcad
    - Maxodactyl
    - forzesed
    - caseprince

  channel:
    "#deathclaw-core"

  quotes:
    - ":wave:"

lighthouse:
  members:
    - chris-grabcad
    - NigelAtGrabCAD
    - robert-may1
    - EmaParodi
    - zhelezina

  channel:
    "#lighthouse"

  quotes:
    - ":wave:"

machine:
  members:
    - hmak3d
    - DanielDignam

  channel:
    "#machine"

  quotes:
    - ":wave:"

octopus:
  members:
    - arielhad
    - csidorchuk
    - mklchum
    - adigrabcad

  channel:
    "#octopus"

  quotes:
    - ":wave:"

octopusanubis:
  members:
    - EyalRaz
    - Jittery
    - TamirYanko
    - adigrabcad
    - posulliv
    - Ludasha

  channel:
    "#anubis"

  quotes:
    - ":wave:"

solutions:
  members:
    - atardugno
    - vtravieso
    - urimike
    - ShaiTubul
    - yossikoren
    - gilshapirastratasys

  channel:
    "#solutions"

  quotes:
    - ":wave:"

lacheetah:
  members:
    - raidokaldma
    - joras
    - meelispr

  channel:
    "#la-cheetah"

spock:
  members:
    - mlni
    - johannessiig
    - tambet
  channel:
    "#spock-notifications"
