# Please insert new items alphabetically.

tribble:
  members:
    - Maxodactyl
    - caseprince
    - reshadbinharun
    - mwhearty
    - posulliv
    - anju-james

  channel:
    "#tribble-private"

  quotes:
    - ":wave:"

lighthouse:
  members:
    - NigelAtGrabCAD
    - robert-may1
    - DavidJohnMcLean
    - gcmatthewarcus

  channel:
    "#lighthouse"

  quotes:
    - ":wave:"

machine:
  members:
    - hhazi    
    - chris-grabcad

  channel:
    "#machine"

  quotes:
    - ":wave:"

octopus:
  members:
    - arielhad
    - ido-ran
    - Tamara211
    - danielyac
    - manuel-grabcad
    - amPerl
    - YairFuchs
    - dmitri-grabcad

  channel:
    "#octopus"

  quotes:
    - ":wave:"

solutions:
  members:
    - urimike
    - AvivEshed
    - slavashtilerman

  channel:
    "#solutions"

  quotes:
    - ":wave:"

spock:
  members:
    - johannessiig
    - tambet
  channel:
    "#spock-notifications"

jackalope:
  members:
    - mrk252
    - dangrabcad
    - TiptonBR
    - evan-grabcad
    - atardugno
    - vtravieso
    - RobertMJ

  channel:
    "#jackalope"
    
alpha:
  members:
    - jaySSYS
    - erikheide
    - deyaoren
    
  channel:
    "#alpha"
    
geometry:
  members:
    - NigelAtGrabCAD
    - robert-may1
    - hhazi
    - dangrabcad
    - atardugno
    - vtravieso
    - jeffmisu
    - TiptonBR
    - mrk252
    - DavidJohnMcLean
    - gcmatthewarcus

  channel:
    "#geometry"

  quotes:
    - ":wave:"
